### PR TITLE
fix(plugins): plugins not found in monorepo

### PR DESCRIPTION
**Pull request by scorsi**
## Thank you for helping out! ✨

This commit helps runs the inventory plugin loader inside a monorepo (tested with nrwl nx and turborepo using npm, pnpm and yarn).

### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by ryanblock** [comment]
Hi! Can you tell me more about the intention of this PR and what it solves?

**Comment by scorsi** [comment]
> Hi! Can you tell me more about the intention of this PR and what it solves?

Hello, in a monorepo project, the `nodes_modules` are not presents in the actual architect project directory (i.e. in `./apps/account-service`) but in the root of the monorepo (i.e. `../../` if we are in the project directory).

To explain, here a brief of the actual implementation:
```js
function getPath (cwd, srcDir, name) {
  let path1 = join(cwd, 'src', srcDir, `${name}.js`)
  let path2 = join(cwd, 'src', srcDir, name)
  let path3 = join(cwd, 'node_modules', name)
  let path4 = join(cwd, 'node_modules', `@${name}`)
  /**/ if (existsSync(path1)) return path1
  else if (existsSync(path2)) return path2
  else if (existsSync(path3)) return path3
  else if (existsSync(path4)) return path4
  try {
    return require.resolve(name)
  }
  catch {
    try {
      return require.resolve(`@${name}`)
    }
    catch {
      return
    }
  }
}
```

If I want to use `@architect/typescript-plugin` I must write `architect/typescript-plugin` in the `app.arc` file of the project, so:
- `path1` is `./src/architect/typescript-plugin.js`, it fails, this is not a file but a node module
- `path2` is `./src/architect/typescript-plugin`, it fails, this is not a file but a node module
- `path3` is `./node_modules/architect/typescript-plugin`, it fails since the node module should have a `@` before
- `path4` is `./node_modules/@architect/typescript-plugin`, should succeed normally but the node module is not in the current directory, because in monorepo, the dependency is in a parent `node_modules` folder, so it fails too
- the first try-catch fails since node can not find any `architect/typescript-plugin` node module in the parent `node_modules` because its name is `@architect/typescript-plugin`
- my addition, the second try-catch adds `@` so node search for a dependency named `@architect/typescript-plugin` and it found it in the parents `node_modules`, succeed.

Thanks,

**Comment by ryanblock** [comment]
Ah ok, cool, that makes sense, thanks!

FYI: you can make this work with no patch by quoting the `@` in the plugin name, like so:
```
@plugins
'@architect/plugin-typescript'
```

That's probably not super widely known though (and iirc we don't call it out in docs) so this patch makes sense. Your implementation works and is simple enough; personally I'd really like to avoid a nested try-catch, but honestly your current patch may ultimately be tidier, wdyt?

Otherwise I think it would be good to see explicit unit tests around this – which, to be fair, I don't think we added when we first implemented this require.resolve a few months back. Not sure how we slipped, but the 100% coverage apparently didn't show that, perhaps because the path is getting run during error / validation tests (https://github.com/architect/inventory/blame/main/test/unit/src/config/pragmas/plugins-test.js). Anyhow, I don't think we are checking any assertions around searching for file paths in this way.

I can think about how we'll go about that if you don't want to take it on, but it would be a little while before I'll get to it!

**Comment by scorsi** [comment]
> FYI: you can make this work with no patch by quoting the `@` in the plugin name, like so:
> 
> ```
> @plugins
> '@architect/plugin-typescript'
> ```
> 
> That's probably not super widely known though (and iirc we don't call it out in docs) so this patch makes sense.

I tried and got error `Plugin names can only contain [a-zA-Z0-9/\\-._]`.

> Your implementation works and is simple enough; personally I'd really like to avoid a nested try-catch, but honestly your current patch may ultimately be tidier, wdyt?

Yeah I'm agreed, tbh, I find the whole function a bit ugly :P

> Otherwise I think it would be good to see explicit unit tests around this – which, to be fair, I don't think we added when we first implemented this require.resolve a few months back. Not sure how we slipped, but the 100% coverage apparently didn't show that, perhaps because the path is getting run during error / validation tests (https://github.com/architect/inventory/blame/main/test/unit/src/config/pragmas/plugins-test.js). Anyhow, I don't think we are checking any assertions around searching for file paths in this way.

I don't have the time to dive into that for the moment, sorry

**Comment by ryanblock** [comment]
> I tried and got error Plugin names can only contain [a-zA-Z0-9/\\-._].

Oof, sorry about that, that's right! Good call.

Ok, merging this, thanks again for the thorough explanation / repro steps.

**Pull request merged**
